language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.2
    - otp_release: 19.0
      elixir: 1.4.2
addons:
  postgresql: '9.4'
services:
  - postgresql
cache:
  directories:
    - _build
    - deps
before_script:
  - mix ecto.create && mix ecto.migrate
  - mix run apps/phoenix_china/priv/repo/seeds.exs
script:
  - mix test