phoenix_china_umbrella:
  build: .
  dockerfile: Dockerfile # That's our Dockerfile path
  command: mix phx.server # Start the server if no other command is specified
  environment:
    - MIX_ENV=prod # That's the environment mode, you know
    - PORT=4000
    - SECRET_KEY_BASE=M)uJej7Ei2rYvw7,fDoskeXYL8[8y(VrvpwuP+g4tYxHz>qV?hkF=P[nsnuJfF>D
  volumes:
    - .:/app # Here we're mounting our project's root directory inside the container
  ports:
    - "4000:4000"
  links:
    - postgres

postgres:
  image: postgres:9.6.2 # https://hub.docker.com/_/postgres/
  ports:
    - "5432"